name: Build LaTeX document
on:
  push:
    branches:
      - '**'
    tags-ignore:
      - '**'
jobs:
  build_latex:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repo
        uses: actions/checkout@v4
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v3
        with:
          root_file: main.tex
          working_directory: manual/
          pre_compile: "tlmgr update --self && tlmgr update --all"
          post_compile: "latexmk -c"
          latexmk_shell_escape: true
      - name: Upload PDF file
        uses: actions/upload-artifact@v4
        with:
          name: Memoria
          path: manual/main.pdf
          compression-level: 9
          overwrite: true
